# Generated by Django 4.2.13 on 2026-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaconfiguration',
            name='content_font',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times Roman'), ('Times-Bold', 'Times Bold'), ('Courier', 'Courier'), ('Courier-Bold', 'Courier Bold')], default='Helvetica-Bold', help_text='Fuente para contenido', max_length=50),
        ),
        migrations.AlterField(
            model_name='facturaconfiguration',
            name='header_font',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times Roman'), ('Times-Bold', 'Times Bold'), ('Courier', 'Courier'), ('Courier-Bold', 'Courier Bold')], default='Helvetica-Bold', help_text='Fuente para encabezados', max_length=50),
        ),
        migrations.AlterField(
            model_name='facturaconfiguration',
            name='total_font',
            field=models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times Roman'), ('Times-Bold', 'Times Bold'), ('Courier', 'Courier'), ('Courier-Bold', 'Courier Bold')], default='Helvetica-Bold', help_text='Fuente para contenido', max_length=50),
        ),
    ]
