# Generated by Django 4.2.13 on 2026-05-19 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_alter_articulo_options_alter_articulo_codigo'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloventa',
            name='precio_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Versión normalizada del precio. Se llena automáticamente a partir del campo `precio` (CharField legacy). Usar este campo en cálculos financieros nuevos.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='articuloventa',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_vendidos', to='articulo.articulo'),
        ),
    ]
