# Generated by Django 4.2.13 on 2026-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='archivada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
