# Generated by Django 4.2.13 on 2026-05-20 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0006_listaprecios_listapreciositem_listaprecios_articulos_and_more'),
        ('venta', '0005_schedule_archivar_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveIntegerField(help_text='Cuántas unidades pidió el operador en la venta.')),
                ('stock_disponible_al_momento', models.IntegerField(help_text='Stock que había justo antes de la venta. Puede ser 0.')),
                ('cantidad_faltante', models.PositiveIntegerField(help_text='cantidad_pedida − stock_disponible_al_momento. > 0 por definición.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisada', models.BooleanField(default=False, help_text='Marcar cuando alguien ya investigó y resolvió la alerta.')),
                ('revisada_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='', help_text='Notas del revisor: qué se hizo, por qué pasó, etc.')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_stock', to='articulo.articulo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_stock', to='venta.venta')),
            ],
            options={
                'verbose_name': 'alerta de stock',
                'verbose_name_plural': 'alertas de stock',
                'ordering': ['revisada', '-created_at'],
                'indexes': [models.Index(fields=['revisada', '-created_at'], name='venta_alert_revisad_a00453_idx')],
            },
        ),
    ]
