# Generated by Django 4.2.13 on 2026-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_alertastock_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto cobrado al registrar el pago. NULL = aún no se registró pago. Cualquier valor = idempotente: la acción "Registrar pago" no vuelve a aplicarse sobre este pedido.', max_digits=12, null=True),
        ),
    ]
