# Generated by Django 4.2.13 on 2026-08-29 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copiar_direccion_legacy_a_pedidos(apps, schema_editor):
    Pedido = apps.get_model('venta', 'Pedido')
    DireccionCliente = apps.get_model('cliente', 'DireccionCliente')
    direcciones = {
        direccion.cliente_id: direccion
        for direccion in DireccionCliente.objects.filter(es_principal=True)
    }
    pendientes = []
    campos = [
        'direccion_entrega', 'direccion_entrega_texto',
        'localidad_entrega', 'provincia_entrega', 'referencia_entrega',
        'latitud_entrega', 'longitud_entrega', 'direccion_confirmada',
    ]
    for pedido in Pedido.objects.select_related('venta').all().iterator(chunk_size=500):
        direccion = direcciones.get(pedido.venta.cliente_id)
        if not direccion:
            continue
        pedido.direccion_entrega_id = direccion.pk
        pedido.direccion_entrega_texto = direccion.direccion_texto
        pedido.localidad_entrega = direccion.localidad
        pedido.provincia_entrega = direccion.provincia
        pedido.referencia_entrega = direccion.referencia
        pedido.latitud_entrega = direccion.latitud
        pedido.longitud_entrega = direccion.longitud
        pedido.direccion_confirmada = direccion.confirmada
        pendientes.append(pedido)
        if len(pendientes) >= 500:
            Pedido.objects.bulk_update(pendientes, campos)
            pendientes = []
    if pendientes:
        Pedido.objects.bulk_update(pendientes, campos)


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_direccioncliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendedor', '0003_repartidor'),
        ('venta', '0008_pedido_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entrega_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='asignado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cliente.direccioncliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega_texto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='latitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='localidad_entrega',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_no_entrega',
            field=models.CharField(blank=True, choices=[('cliente_ausente', 'Cliente ausente'), ('direccion_incorrecta', 'Dirección incorrecta o no encontrada'), ('rechazado', 'Cliente rechazó el pedido'), ('faltante_danado', 'Faltantes o productos dañados'), ('otro', 'Otro')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacion_entrega',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia_entrega',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_entrega',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='vendedor.repartidor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('En reparto', 'En reparto'), ('Entregado', 'Entregado'), ('No entregado', 'No entregado'), ('Reprogramado', 'Reprogramado'), ('Listo para retirar', 'Listo para retirar')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, default='', max_length=40)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='venta.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estados_pedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de estado de pedido',
                'verbose_name_plural': 'historial de estados de pedidos',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.RunPython(
            copiar_direccion_legacy_a_pedidos,
            migrations.RunPython.noop,
        ),
    ]
