# Generated by Django 4.2.13 on 2024-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.TextField()),
                ("apellido", models.TextField()),
                (
                    "telefono",
                    models.TextField(blank=True, default="00000000", null=True),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, default="direccion", max_length=50, null=True
                    ),
                ),
                (
                    "codigo_interno",
                    models.CharField(
                        blank=True, default="no-codigo", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
            },
        ),
    ]
