# Generated by Django 4.2.13 on 2026-05-19 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_descuentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'cuenta corriente',
                'verbose_name_plural': 'cuentas corrientes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta_a_cuenta', 'Venta a cuenta'), ('pago', 'Pago recibido'), ('ajuste', 'Ajuste manual'), ('aplicacion_saldo', 'Aplicación de saldo'), ('excedente_venta', 'Excedente de venta')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Positivo = a favor del cliente. Negativo = el cliente debe.', max_digits=12)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cliente.cuentacliente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='venta.venta')),
            ],
            options={
                'verbose_name': 'movimiento de cuenta',
                'verbose_name_plural': 'movimientos de cuenta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cuenta', 'created_at'], name='cliente_mov_cuenta__5b1bfc_idx')],
            },
        ),
    ]
