# Generated by Django 4.2.13 on 2026-05-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0002_alter_articulo_options_alter_articulo_codigo'),
        ('venta', '0003_descuentos'),
        ('cliente', '0003_backfill_cuentacliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_pactados', to='articulo.articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_pactados', to='cliente.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venta_origen', models.ForeignKey(blank=True, help_text='Venta en la que se cerró por primera vez este precio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_pactados_generados', to='venta.venta')),
            ],
            options={
                'verbose_name': 'precio pactado',
                'verbose_name_plural': 'precios pactados',
                'indexes': [models.Index(fields=['cliente'], name='cliente_pre_cliente_82b534_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='preciocliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'articulo'), name='precio_unico_por_cliente_articulo'),
        ),
    ]
