# Generated by Django 4.2.13 on 2026-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_preciocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Solo dígitos, con código de país. Ej: 5491155551234', max_length=20),
        ),
    ]
