# Generated by Django 4.2.13 on 2026-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_backfill_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puede_recibir_whatsapp',
            field=models.BooleanField(default=False, help_text='Si está marcado, el cliente recibe campañas de WhatsApp. Si no, queda excluido de la audiencia aunque tenga número cargado. Cambiar por consentimiento explícito.'),
        ),
    ]
