# Generated by Django 4.2.13 on 2026-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cliente_puede_recibir_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='formato_preferido_lista_precios',
            field=models.CharField(blank=True, choices=[('link', 'Solo link público (siempre actualizado)'), ('pdf', 'Solo PDF adjunto (queda en el chat)'), ('ambos', 'Ambos: PDF + link debajo')], default='', help_text='Cómo prefiere este cliente recibir la lista de precios. Si queda vacío, se usa el default global de Configuración. Si elegís uno acá, se aplica salvo que el operador lo pise al difundir.', max_length=10),
        ),
    ]
