# Generated by Django 4.2.13 on 2026-05-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_cliente_formato_preferido_lista_precios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioSaldoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_snapshot', models.DecimalField(decimal_places=2, help_text='Monto del saldo al momento del recordatorio (negativo = debe).', max_digits=12)),
                ('dias_desde_ultima_compra', models.PositiveIntegerField(blank=True, help_text='Días desde la última compra del cliente al momento del recordatorio.', null=True)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], default='enviado', max_length=10)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_saldo', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'recordatorio de saldo enviado',
                'verbose_name_plural': 'recordatorios de saldo enviados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', '-created_at'], name='cliente_rec_cliente_b460ec_idx')],
            },
        ),
    ]
