# Generated by Django 4.2.13 on 2026-06-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_pedido_monto_pagado'),
        ('cliente', '0013_schedule_clientes_inactivos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertaclienteinactivo',
            new_name='cliente_ale_cliente_60b689_idx',
            old_name='cliente_ale_cliente_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='alertaclienteinactivo',
            new_name='cliente_ale_revisad_6ca0c4_idx',
            old_name='cliente_ale_revisad_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='movimientocuenta',
            name='pedido_origen',
            field=models.OneToOneField(blank=True, help_text='Pedido cuyo "monto_pagado" generó este movimiento. Si está seteado, este es el pago canónico de ese pedido y se edita/borra automáticamente cuando el operador cambia el campo monto_pagado del pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_pago', to='venta.pedido'),
        ),
    ]
