# Generated by Django 4.2.13 on 2026-08-29 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def crear_direcciones_legacy(apps, schema_editor):
    Cliente = apps.get_model('cliente', 'Cliente')
    DireccionCliente = apps.get_model('cliente', 'DireccionCliente')
    nuevas = []
    for cliente in Cliente.objects.all().iterator(chunk_size=500):
        texto = (cliente.direccion or '').strip()
        if not texto or texto.lower() == 'direccion':
            continue
        nuevas.append(DireccionCliente(
            cliente_id=cliente.pk,
            etiqueta='Principal',
            direccion_texto=texto,
            fuente='legacy',
            confirmada=False,
            es_principal=True,
        ))
        if len(nuevas) >= 500:
            DireccionCliente.objects.bulk_create(nuevas)
            nuevas = []
    if nuevas:
        DireccionCliente.objects.bulk_create(nuevas)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0014_rename_cliente_ale_cliente_a1b2c3_idx_cliente_ale_cliente_60b689_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(default='Principal', max_length=60)),
                ('direccion_texto', models.CharField(blank=True, default='', max_length=255)),
                ('localidad', models.CharField(blank=True, default='', max_length=120)),
                ('provincia', models.CharField(blank=True, default='', max_length=120)),
                ('referencia', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('precision_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('fuente', models.CharField(choices=[('legacy', 'Importada del campo anterior'), ('gps', 'Ubicación GPS'), ('manual', 'Carga manual'), ('geocodificada', 'Dirección geocodificada')], default='manual', max_length=20)),
                ('confirmada', models.BooleanField(default=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='cliente.cliente')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direcciones_cliente_confirmadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dirección de cliente',
                'verbose_name_plural': 'direcciones de clientes',
                'ordering': ('-es_principal', '-actualizada_en'),
            },
        ),
        migrations.AddConstraint(
            model_name='direccioncliente',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('cliente',), name='una_direccion_principal_por_cliente'),
        ),
        migrations.RunPython(
            crear_direcciones_legacy,
            migrations.RunPython.noop,
        ),
    ]
