# Generated by Django 4.2.13 on 2026-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas_retencion_meses', models.PositiveIntegerField(default=18, help_text='Cantidad de meses a partir de los cuales una venta se archiva automáticamente. NO se borra: solo queda oculta del listado normal del admin (visible con filtro "Archivadas"). El cron `archivar_ventas_antiguas` usa este valor.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración general',
                'verbose_name_plural': 'configuración general',
            },
        ),
    ]
