# Generated by Django 4.2.13 on 2026-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_sheets_sync_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='formato_default_lista_precios',
            field=models.CharField(choices=[('link', 'Solo link público (más fresco)'), ('pdf', 'Solo PDF adjunto (queda guardado)'), ('ambos', 'Ambos: PDF + link debajo')], default='link', help_text='Cómo se mandan las listas de precios por defecto en una difusión. Recomendado "Solo link" para que siempre llegue actualizado. Cada cliente puede tener su preferencia propia, y al difundir el operador puede pisar este default.', max_length=10),
        ),
    ]
