# Generated by Django 4.2.13 on 2026-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuraciongeneral_formato_default_lista_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='recordatorios_saldo_dias_inactividad',
            field=models.PositiveIntegerField(default=30, help_text='Días sin compras para considerar "inactivo" y candidato a recordatorio. Default 30. Si bajás esto, le va a llegar a más gente (incluyendo clientes que están al día y simplemente no compraron esta semana).'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='recordatorios_saldo_frecuencia_dias',
            field=models.PositiveIntegerField(default=7, help_text='Días mínimos entre recordatorios al mismo cliente. Default 7 (una vez por semana). Si el cron corre todos los días, este campo evita spamear al mismo cliente todos los días.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='recordatorios_saldo_habilitado',
            field=models.BooleanField(default=False, help_text='Si está prendido, una vez por semana (configurable abajo) se mandan WhatsApps a clientes con saldo deudor sin compras recientes. Apagalo cuando no quieras que se manden — el schedule sigue corriendo pero hace NO-OP.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='recordatorios_saldo_monto_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solo recordar saldos deudores mayores a este monto. 0 = recordar a todos los deudores. Útil para no molestar por deudas menores ($100, $200) que no compensan el ruido.', max_digits=12),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='recordatorios_saldo_template',
            field=models.TextField(default='Hola {{nombre}}, te recuerdo que tenés un saldo pendiente de ${{saldo_abs}} desde hace {{dias}} días. Cualquier cosa avisame.', help_text='Template del mensaje. Variables: {{nombre}}, {{saldo_abs}} (monto positivo de la deuda), {{dias}} (días desde última compra).'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='recordatorios_saldo_ultima_corrida_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo corrió por última vez la task (read-only).', null=True),
        ),
    ]
