# Generated by Django 4.2.13 on 2026-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_configuraciongeneral_formato_default_lista_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='auto_responder_habilitado',
            field=models.BooleanField(default=False, help_text='Si está prendido, cuando un cliente le manda al bot "lista" o "saldo" le respondemos automáticamente. Ahorra responder lo mismo todos los días. NO responde a números desconocidos.'),
        ),
    ]
