# Generated by Django 4.2.13 on 2026-07-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0010_alerta_inactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_articulos',
            field=models.BooleanField(default=True, help_text='Mostrar el detalle de artículos + cantidades de cada pedido. Si está apagado, solo se muestra la fila-resumen sin desglose.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_cliente',
            field=models.BooleanField(default=True, help_text='Mostrar la columna con el nombre del cliente.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_cobro',
            field=models.BooleanField(default=True, help_text='Mostrar el estado de cobro (pagado / pendiente) y el total adeudado del vendedor abajo del informe.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_direccion',
            field=models.BooleanField(default=False, help_text='Mostrar la dirección del cliente. Útil si el vendedor usa el informe también como hoja de reparto.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_total',
            field=models.BooleanField(default=True, help_text='Mostrar la columna con el total en pesos de cada pedido.'),
        ),
    ]
