# Generated by Django 4.2.13 on 2026-07-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0011_configuraciongeneral_informe_diario_incluir_articulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_totales_cobro',
            field=models.BooleanField(default=True, help_text='Mostrar la línea "Cobrado / Pendiente" en la cabecera con los subtotales del día. Independiente del checkbox anterior — podés querer los totales en la cabecera sin la columna, o al revés.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_titulo',
            field=models.CharField(default='Informe diario por vendedor', help_text='Texto del encabezado principal del PDF. Va centrado arriba, seguido del nombre del vendedor y la fecha. Cambialo si querés poner el nombre del negocio (ej. "Golosinas Insa — Cierre diario").', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_cobro',
            field=models.BooleanField(default=True, help_text='Mostrar una columna extra con el estado de cobro de cada pedido: ✔ Pagado o ● Pendiente.'),
        ),
    ]
