# Generated by Django 4.2.13 on 2026-07-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0012_configuraciongeneral_informe_diario_incluir_totales_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_total_dia',
            field=models.BooleanField(default=False, help_text='Mostrar la línea "Total del día: $XXX" en la cabecera. Es la suma bruta de todos los pedidos del vendedor ese día. Apagado por default porque muchas veces el cierre del día se discute con Cobrado/Pendiente aparte y este total repetido confunde.'),
        ),
    ]
