# Generated by Django 4.2.13 on 2026-07-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_configuraciongeneral_informe_diario_incluir_total_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='informe_diario_incluir_formas_pago',
            field=models.BooleanField(default=True, help_text='Agregar una columna con 3 casillas vacías por pedido para tildar a mano cómo se cobró: transferencia, efectivo o cuenta corriente. Útil como planilla de conciliación al cierre del día.'),
        ),
    ]
