# Generated by Django 4.2.13 on 2024-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articulo",
            options={"ordering": ["codigo"]},
        ),
        migrations.AlterField(
            model_name="articulo",
            name="codigo",
            field=models.CharField(max_length=255),
        ),
    ]
