# Generated by Django 4.2.13 on 2026-05-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_alter_articulo_options_alter_articulo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#607d8b', help_text='Color hex (ej. #2196f3) para mostrar la categoría en badges.', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras_clave', models.JSONField(default=list, help_text='Lista de strings. Si el nombre del artículo contiene cualquiera (case-insensitive), se le asigna esta categoría. Ej: ["alfajor", "chupetin", "chicle"]')),
                ('prioridad', models.PositiveIntegerField(default=100, help_text='Menor número = mayor prioridad. Útil para resolver ambigüedad cuando dos reglas matchean el mismo artículo.')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='articulo.categoria')),
            ],
            options={
                'verbose_name': 'regla de categoría',
                'verbose_name_plural': 'reglas de categoría',
                'ordering': ['prioridad', 'categoria__nombre'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='articulo.categoria'),
        ),
    ]
