# Generated by Django 4.2.13 on 2026-05-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_proveedor_direccion_alter_proveedor_telefono'),
        ('articulo', '0004_seed_categorias_y_reglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='compra.proveedor'),
        ),
    ]
