# Generated by Django 4.2.13 on 2026-05-20 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0007_cliente_puede_recibir_whatsapp'),
        ('articulo', '0005_articulo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Etiqueta interna ("Lista marzo", "Promo navidad", etc.)', max_length=120)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Descuento adicional aplicado a TODA la lista (sobre el precio que ya considera PrecioCliente si lo hay). 0 = sin descuento extra.', max_digits=5)),
                ('descuento_motivo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lista de precios',
                'verbose_name_plural': 'listas de precios',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListaPreciosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nota', models.CharField(blank=True, default='', max_length=120)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulo.articulo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='articulo.listaprecios')),
            ],
            options={
                'verbose_name': 'item de lista de precios',
                'verbose_name_plural': 'items de lista de precios',
                'ordering': ['orden', 'articulo__nombre'],
            },
        ),
        migrations.AddField(
            model_name='listaprecios',
            name='articulos',
            field=models.ManyToManyField(related_name='listas_precios', through='articulo.ListaPreciosItem', to='articulo.articulo'),
        ),
        migrations.AddField(
            model_name='listaprecios',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='listaprecios',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='listapreciositem',
            constraint=models.UniqueConstraint(fields=('lista', 'articulo'), name='un_articulo_por_lista'),
        ),
        migrations.AddIndex(
            model_name='listaprecios',
            index=models.Index(fields=['cliente', '-updated_at'], name='articulo_li_cliente_1352dd_idx'),
        ),
    ]
