# Generated by Django 4.2.13 on 2026-05-20 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0008_cliente_formato_preferido_lista_precios'),
        ('articulo', '0009_articulo_codigo_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecios',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Magnitud del ajuste porcentual aplicado a TODA la lista, siempre positiva (0-100). Si querés AUMENTO en vez de descuento, cambiá `tipo_ajuste`. El campo no se renombró para no romper datos / APIs viejas.', max_digits=5),
        ),
        migrations.CreateModel(
            name='DifusionListaPreciosEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('link', 'Solo link'), ('pdf', 'Solo PDF'), ('ambos', 'PDF + link')], max_length=10)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('telefono_usado', models.CharField(blank=True, default='', max_length=20)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_difusion_lista', to='cliente.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_difusion', to='articulo.listaprecios')),
            ],
            options={
                'verbose_name': 'envío de difusión de lista',
                'verbose_name_plural': 'envíos de difusión de lista',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='articulo_di_status_4442c1_idx'), models.Index(fields=['lista', '-created_at'], name='articulo_di_lista_i_93f8cf_idx')],
            },
        ),
    ]
