# Generated by Django 4.2.13 on 2026-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0010_alter_listaprecios_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difusionlistapreciosenvio',
            name='modo',
            field=models.CharField(choices=[('texto', 'Solo texto'), ('link', 'Solo link'), ('pdf', 'Solo PDF'), ('ambos', 'PDF + link')], max_length=10),
        ),
    ]
