# Generated by Django 4.2.13 on 2026-05-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_alter_cliente_formato_preferido_lista_precios'),
        ('articulo', '0011_alter_difusionlistapreciosenvio_modo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudListaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_original', models.TextField(blank=True, default='')),
                ('resuelta', models.BooleanField(default=False, help_text='Marcar cuando la lista esté armada o se decida ignorar.')),
                ('resuelta_at', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='', help_text='Opcional: por qué se resolvió de tal manera, qué lista se le armó, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_lista', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'solicitud de lista',
                'verbose_name_plural': 'solicitudes de lista',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resuelta', '-created_at'], name='articulo_so_resuelt_ab456e_idx'), models.Index(fields=['cliente', 'resuelta'], name='articulo_so_cliente_19da10_idx')],
            },
        ),
    ]
