# Generated by Django 4.2.13 on 2026-05-19 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_backfill_whatsapp_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('mensaje', models.TextField(help_text='Template del mensaje. Variables: {{nombre}}, {{apellido}}, {{saldo}}')),
                ('adjunto', models.FileField(blank=True, help_text='Imagen (JPG/PNG) o PDF. Opcional.', null=True, upload_to='wa_campania/adjuntos/')),
                ('audiencia_filtro', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviando', 'Enviando'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviada_at', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'campaña de WhatsApp',
                'verbose_name_plural': 'campañas de WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvioWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_usado', models.CharField(default='', max_length=20)),
                ('mensaje_renderizado', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='wa_campania.campania')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_whatsapp', to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'envío de WhatsApp',
                'verbose_name_plural': 'envíos de WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='wa_campania_status_f415ab_idx'), models.Index(fields=['campania', 'status'], name='wa_campania_campani_22bfcd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='enviowhatsapp',
            constraint=models.UniqueConstraint(fields=('campania', 'cliente'), name='un_envio_por_cliente_por_campania'),
        ),
    ]
